language: ruby
rvm:
- 2.2.0
- APIKEY="23e5d3518fa5ffb4fc3e64b19ca54863"
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: QrqEm60bxXc9S7Jx7NOtlbNMVM+E7M73DtS/wzWR/GQvXQjZBaOCW/dtYS9PojajwzQ8S9k59j2MuyaoK5I3FozKvCetic727+2m3fBBUkfACXzzqomvDLrO14wdBY3vM8xjerApr0OtnYWo94r2uOQx+HwVfb/LlI3zvX51mtU=
  	APIKEY: 23e5d3518fa5ffb4fc3e64b19ca54863
  skip_cleanup: true
  app: immense-badlands-5135
  on:
    repo: henrima/ratebeer
